<h1>Employee listing</h1>
<a href="<?php echo $block->getUrl('employee/employeecontroller/employee1')?>">Add New + </a>

<h2 style="background-color:powderblue;color:blue;text-align:center;"><strong>Magento 2 CRUD Operations</strong></h2>
<?php  $data = $block->loadEmployeeCollection(); ?>

<table>
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>City</th>
        <th>Mobile</th>
        <th>Image</th>
        <th>Created Date</th>
        <th>Action</th>
    </tr>
    <?php foreach ($data as $key => $emp) { ?>
   
        <tr>
        
            <td><?php echo $emp['name']; ?></td>
            <td><?php echo $emp['email']; ?></td>
            <td><?php echo $emp['city']; ?></td>
            <td><?php echo $emp['mobile']; ?></td>
            <td><img src="<?php echo $block->getUrl().'pub/media/tmp/image/'. $emp['image'];?>" height="50px" width="50px"/></td>
            <td><?php echo $emp['created_at']; ?></td>
            <td><a href="<?php echo $block->getUrl('employee/employeecontroller/edit').'?id='.$emp['id']; ?>">Edit</a>
            <a href="<?php echo $block->getUrl('employee/employeecontroller/delete').'?id='.$emp['id']; ?>">Delete</a></td>
        </tr>    

    <?php }?>
</table>