<h1>Enter Details</h1>
<a href="<?php echo $block->getUrl('teacher/teachercontroller3/teacher3')?>">View All</a>
<form action="<?= $block->getUrl('teacher/teachercontroller2/teacher2'); ?>" method="POST">

      <label for="name">Enter Your Name:</label>
    <input type="text" id="name" name="name"><br><br>

    <label for="email">Enter Your Email Address:</label>
    <input type="text" id="email" name="email"><br><br>

    <label for="qualification">Qualification:</label>
    <input type="text" id="qualification" name="qualification"><br><br>

    <label for="department">Department:</label>
    <input type="text" id="department" name="department"><br><br>


    <label for="phone">Phone:</label>
    <input type="text" id="phone" name="phone"><br><br>

  <input type="submit" value="Submit">

</form>