<?php
$data = $block->getEditData();
?>

<h1>Update Details</h1>
<form action="<?= $block->getUrl('teacher/teachercontroller6/teacher6').'?id='.$data['id']; ?>" method="POST">
      <label for="name">Enter Your Name:</label>
    <input type="text" id="name" name="name" value="<?php echo $data['name']; ?>"><br><br>

    <label for="email">Enter Your Email Address:</label>
    <input type="text" id="email" name="email" value="<?php echo $data['email']; ?>"><br><br>

    <label for="qualification">Qualification:</label>
    <input type="text" id="qualification" name="qualification" value="<?php echo $data['qualification']; ?>"><br><br>

    <label for="department">Department:</label>
    <input type="text" id="department" name="department" value="<?php echo $data['department']; ?>"><br><br>


    <label for="phone">Phone:</label>
    <input type="text" id="phone" name="phone" value="<?php echo $data['department']; ?>"><br><br>

  <input type="submit" value="update">
</form>


