<h1>Teacher Listing</h1>
<a href="<?php echo $block->getUrl('teacher/teachercontroller1/teacher1')?>">Add New +</a>
<?php  $data = $block->loadTeacherCollection(); ?>
<table>
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Qualification</th>
        <th>Department</th>
        <th>Created Date</th>
        <th>Action</th>
    </tr>
    <?php foreach ($data as $key => $emp) { ?>
        <tr>
            <td><?php echo $emp['name']; ?></td>
            <td><?php echo $emp['email']; ?></td>
            <td><?php echo $emp['qualification']; ?></td>
            <td><?php echo $emp['department']; ?></td>
            <td><?php echo $emp['created_at']; ?></td>     
            <td>
            <a href="<?php echo $block->getUrl('teacher/teachercontroller5/teacher5').'?id='.$emp['id']; ?>">Edit</a>
           /
            <a href="<?php echo $block->getUrl('teacher/teachercontroller4/delete').'?id='.$emp['id']; ?>">Delete</a>
         </td>        
        </tr>    
    <?php }?>
</table>




